### ISSUE TITLE
Issue firebase config file

### ISSUE THREAD

**Issue by Titogelo** [rafaelklaessen/keep-clone#12]
I still have the issue with the path to read the config json for firebase. 
Maybe there is a way to load the firebase config json more efficiently using dependency injection.

Please have a look at the following documentation, you might find something interesting there: https://www.playframework.com/documentation/2.5.x/ScalaDependencyInjection

**Comment by rafaelklaessen** [comment]
No, the file has to be a FileInputStream, but I found what the problem is.
Apparently, the file executes from a different path than the path it's placed in. So, I have to fix the path to the Firebase config. I'm working on it.

**Comment by rafaelklaessen** [comment]
I have no clue though why the old file worked...

**Comment by Titogelo** [comment]
Okay, give it a try. But dealing with relative/absolute paths is not optimal. You are 'harcoding' your code.

I suggest you to look up the concept of Dependency Injection. Most of the frameworks use it for this specific purpose (to inject config value in any point of the application). 

Anyway, first try to solve it following your instinct and then if you want to learn more you can have a look at this resource ;)

http://stackoverflow.com/questions/36972305/play-2-5-3-using-dependency-injection-to-get-configuration-values

**Comment by rafaelklaessen** [comment]
Does it work now @Titogelo ? For me it does, but the old file also worked for no reason...

**Comment by Titogelo** [comment]
Yeah, now it works 👍
