### ISSUE TITLE
Persist user notes in DB

### ISSUE THREAD

**Issue by Titogelo** [rafaelklaessen/keep-clone#15]
Look really nice so far! Good job! 
Next step... I would say persist users notes in firebase right? 
I have a couple of questions about this. 
1) Are you going to enable for this first version user notes or all the notes will be shared by all users?
2) If every user will have his/her own notes then later there should be a way to share them with other users (the interesting part of this version is to see how you would deal with the user-note relationship in firebase. 
3) If everyone shares the notes it will be interesting how firebase deals with multiple users editing a note. (I think this one is more interesting if you want to learn more) 

What do you think?

**Comment by rafaelklaessen** [comment]
I'm planning on making user notes (every user has his own notes).
I'd save the relationship in the user _and_ in the note itself. Which I mean by that every user has a field containing the IDs of his notes, and that each note has an owners field. (For explanation why see https://firebase.google.com/docs/database/admin/structure-data, at the bottom.)

Adding note sharing later wouldn't be hard.

**Comment by Titogelo** [comment]
Perfect ;) Well backed up your idea with the firebase documentation 👍 . This is how professionals do their job. 

Just one consideration for later, make sure you keep everything consistent for instance when revoking user's access to a note or when sharing a note with a user. The information must be updated in the user and also in the notes. I am sure you were already thinking about this.

Good job!
