### ISSUE TITLE
Objectify Firebase stuff

### ISSUE THREAD

**Issue by rafaelklaessen** [rafaelklaessen/keep-clone#17]
Instead of returning like Array[Map[String, Array[String]]]

**Comment by rafaelklaessen** [comment]
Apparently Firebase can't read the Scala class fields. I was only able to make them a little more object oriented.

**Comment by Titogelo** [comment]
I don't have a lot of time today. But let's say if I can help you here. 

There is a problem of concept with your approach. As far I read and I understood from the documentation there is no need to keep a parallel data structure in your local.

Firebase works with a database reference that stores your data. Any function from the CRUD ( create, read, update, delete) is applied to this database reference. 

Read this documentation: 
- https://firebase.google.com/docs/database/android/read-and-write
- https://www.firebase.com/docs/web/guide/saving-data.html
- http://stackoverflow.com/questions/32960805/firebase-anyway-not-to-have-whole-server-data-base-mirrored-locally

I hope I am not wrong it is also my first time with this, and I also hope that it helps.

**Comment by Titogelo** [comment]
I didn't take a look at your code but I am replying just from your comments.

**Comment by rafaelklaessen** [comment]
What I mean is that I tried to use the User class for saving users to the database (rather than using .setValue for all the child fields), but that Firebase can't read its fields even though they're public.

**Comment by rafaelklaessen** [comment]
Okay, I fixed it! If we use getters instead of just public fields, it _does_ work. Guess it's some Scala->Java thingy.

**Comment by rafaelklaessen** [comment]
I've made the user registering OO with getters. However, the notes work a bit different so I don't know about that yet.
