### ISSUE TITLE
Add logs to .gitignore 

### ISSUE THREAD

**Issue by Titogelo** [rafaelklaessen/keep-clone#2]
Unless you have a specific reason, don't put logs or sensitive information in github

**Comment by rafaelklaessen** [comment]
You're right. I'll remove .sbtserver.

**Comment by Titogelo** [comment]
Whenever you commit a change to solve an issue (or just related to an issue) use the following notation. 

git commit -m "fixed #2" => if you want to close it 
git commit -m "#2 working on the log issue. not finished yet" => if you are still working on it but the issue is not closed yet.

Check documentation for commits, it is quite powerful: https://help.github.com/categories/commits/
