### ISSUE TITLE
Login: OAuth

### ISSUE THREAD

**Issue by Titogelo** [rafaelklaessen/keep-clone#3]
What about using OAuth protocol?

Then you could have google, facebook, twitter, github login integrated. 

Oauth 2.0 will help you in several ways:

1) authorization and authentication takes place outside your app so you don't need to worry about it.
2) you avoid security issues. Passwords, salts, hash...

**Comment by rafaelklaessen** [comment]
That's interesting, but for the sake of learning how to use Play, I'd prefer making a custom login system. Maybe we could add it later?

**Comment by Titogelo** [comment]
Sure, maybe for version 2 then ;)

**Comment by rafaelklaessen** [comment]
I'm planning on making a Google signin and Github signin button. I'm looking into Facebook & Twitter.

**Comment by Titogelo** [comment]
Nice, give it a try and if you need it I can help you. But first give it a try ;)

**Comment by rafaelklaessen** [comment]
Working on it! Google sign-in works but it's buggy as it's not done yet.
https://github.com/rafaelklaessen/keep-clone/commit/b8f0c74a202549479ef56f8d7233943273490784

**Comment by rafaelklaessen** [comment]
Turns out Twitter doesn't use OAuth 2. Won't implement it (finding the right libraries is also hard, given the fact that nothing's working properly).

**Comment by rafaelklaessen** [comment]
I'm going to try to add Facebook now.

**Comment by rafaelklaessen** [comment]
Facebook's added as well. 
The OAuth basics are now working. I'm going to look into error handling (and some code cleanup where required...) and after that's done, we have OAuth 😄

**Comment by Titogelo** [comment]
Well done! 

I follow your updates here, unfortunately I don't have that much time now to look into the code.
