### ISSUE TITLE
Sensitive information 

### ISSUE THREAD

**Issue by Titogelo** [rafaelklaessen/keep-clone#4]
This is project is a playground, but we need to be careful to not add sensitive information to github. 

One example is this json config file with all the secrets and token for firebase ;)

https://github.com/rafaelklaessen/keep-clone/blob/master/app/keep-clone-840b5-firebase-adminsdk-ztnub-40397c0ba3.json

**Comment by rafaelklaessen** [comment]
I'll remove the JSON file and database secret in the Users model.

**Comment by Titogelo** [comment]
Hey man!

Get some rest ; ) It is weekend.

You are a really hard worker!! But we also need to rest haha

See u!

Best,
Angel.

**Comment by rafaelklaessen** [comment]
Yeah, well, my local git repo's going crazy. I'll look at it tomorrow then.

**Comment by Titogelo** [comment]
Why is it going crazy? I know that sometimes git can give you some headaches... be patient 👍

**Comment by rafaelklaessen** [comment]
I had a detached head because I didn't sync your changes... I just backed everything up and recloned the repo. It works now :)

**Comment by Titogelo** [comment]
Yep, I understand you problem and it is completely fine to have them, so don't worry :). 

Below some tips.

Whenever you work in a collaborative project, you always need to have in mind that more people will be working with your code and also, think that more people might be actually changing other parts of the code while you work. So lot of things can occur in parallel. 

That's why whenever you want to push something to the Github repository you first need to check if there are changes from other team members. 

git pull origin master => to download and merge changes from other people should be okay. 

Talk to you later!

**Comment by JetseVerschuren** [comment]
The json file is still online.
https://github.com/rafaelklaessen/keep-clone/blob/4d9c35843b581b9aaa62a1a9b4d60a4bf4ed4172/app/keep-clone-840b5-firebase-adminsdk-ztnub-40397c0ba3.json
