### ISSUE TITLE
Usernames containing dots causes an error

### ISSUE THREAD

**Issue by rafaelklaessen** [rafaelklaessen/keep-clone#9]
In the getUser method, because the request to Firebase's REST returns 400 if there's a dot.

**Comment by Titogelo** [comment]
You can just validate the registration form and make sure that users avoid dots in their usernames

**Comment by rafaelklaessen** [comment]
Yes, that's possible. I'll look into it. 
I might need to write some additional form verification stuff as well, so that'd be no problem.
